/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import business.security.Autenticacion;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author HP Pavilion
 */
public class FormSignin extends javax.swing.JFrame {

    /**
     * Creates new form IniciodeSesion
     */
    public FormSignin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLOficinaVirtual = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jTContraseña = new javax.swing.JTextField();
        BAcceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");
        setName("Frame1"); // NOI18N
        setResizable(false);

        jLOficinaVirtual.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLOficinaVirtual.setText("Oficina Virtual");

        jLUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLUsuario.setText("Usuario:");

        jLContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLContraseña.setText("Contraseña:");

        jTUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTUsuarioKeyReleased(evt);
            }
        });

        jTContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTContraseñaKeyReleased(evt);
            }
        });

        BAcceder.setText("Acceder");
        BAcceder.setEnabled(false);
        BAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAccederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLOficinaVirtual))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BAcceder)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLContraseña)
                                    .addComponent(jLUsuario))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jTUsuario))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLOficinaVirtual)
                        .addGap(18, 18, 18)
                        .addComponent(jLUsuario))
                    .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContraseña)
                    .addComponent(jTContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BAcceder)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Iniciar Sesion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTUsuarioKeyReleased
        String username = jTUsuario.getText();   //Obtiene el usuario
        String password = jTContraseña.getText();  //Obtiene la contraseña
        
         if (username.isEmpty() || password.isEmpty()){
            BAcceder.setEnabled(false);
        }
        else{
            BAcceder.setEnabled(true);
        }
        
    }//GEN-LAST:event_jTUsuarioKeyReleased

    private void jTContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTContraseñaKeyReleased
        String username = jTUsuario.getText();   //Obtiene el usuario
        String password = jTContraseña.getText();  //Obtiene la contraseña
        
         if (username.isEmpty() || password.isEmpty()){
            BAcceder.setEnabled(false);
        }
        else{
            BAcceder.setEnabled(true);
        }
    }//GEN-LAST:event_jTContraseñaKeyReleased

    private void BAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAccederActionPerformed
        String username = jTUsuario.getText(); //Obtiene el usuario
        String password = new String(jTContraseña.getText()); //Obtiene la contraseña

        Autenticacion auth = new Autenticacion(); //Crea un objetos, para obtener los metodos de la clase
        long id = auth.signin(username, password);

        if (id != -1) {
        this.dispose();
         } else {   
             try {
            ObjectMapper objectMapper = new ObjectMapper();
            File file = new File("src/main/java/data/Usuario.json");
            Usuario user = objectMapper.readValue(file, Usuario.class);

            if (!user.getUsername().equals(username) && !user.getPassword().equals(password) ) {
               JOptionPane.showMessageDialog(this, "USUARIO Y CONTRASEÑA INCORRECTO", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else
            {
               if (!user.getUsername().equals(username)) {
               JOptionPane.showMessageDialog(this, "USUARIO INCORRECTO", "ERROR", JOptionPane.ERROR_MESSAGE);
               }else
               {
               JOptionPane.showMessageDialog(this, "CONTRASEÑA INCORRECTO", "ERROR", JOptionPane.ERROR_MESSAGE);
               }
            }     
            } catch (IOException ex) {
                 System.out.println("ERROR A ACCEDER A LOS DATOS");
            }
 
        }
    }//GEN-LAST:event_BAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSignin().setVisible(true);
            }
        });
    }
    
    public void abrir(){
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAcceder;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLOficinaVirtual;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JTextField jTContraseña;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
